### PR TITLE
create geb-lambdatest plugin to support geb framework

### PR DESCRIPTION
**Pull request by ArpitLT**
Purpose is to Integrate LambdaTest with Geb framework

**[Module Section]**

plugin named "geb-lambdatest" added in file ~/module/geb-core/geb-core.gradle

> apply plugin: "geb-lambdatest"

and added **lambdaTest** task 

> lambdaTest {
>   def applicationAddresses = [8000, 8080, 9000, 9090, 9999].collect { "http://localhost:$it" }
>   application(*applicationAddresses)
>   ...
> }

**[Integration Section]**

 **lambdaTestPlugin** in plugins section [ file : ~/integration/geb-gradle/geb-gradle.gradlegeb-gradle.gradle]

>        lambdaTestPlugin {
>           id = 'geb-lambdatest'
>           implementationClass = 'geb.gradle.lambdatest.LambdaTestPlugin'
>        }

LambdaTestPlugin class follows the basic structure required for geb plugin integration. 
Created task's for **LambdaTest Tunnel** like, 
- downloadLambdaTestTunnel
- unzipLambdaTestTunnel
- openLambdaTestTunnelInBackground
- openLambdaTestTunnel
- closeLambdaTestTunnel

Also, created a test spec named **LambdaTestPluginSpec** [file : ~/integration/geb-gradle/src/test/groovy/geb/gradle/lambdatest/LambdaTestPluginSpec.groovy]

Tested using specific module test command
> ./gradlew :module:geb-core:check

For entire test suite and quality checks, executed
> ./gradlew check

### CODE REVIEW

**Comment by ArpitLT** [comment]
Guys, Any updates !!
Please let us know if anything else required

**Comment by erdi** [comment]
Hi @ArpitLT,

Thanks for your contribution and apologies for taking a while to come back to you. Kudos for following project conventions, most of this can be merged pretty much as is but there are two two things we will need to address:

1. To be able to verify this submission we would need to be able to run some of our tests in LambdaTest as part of our CI. Both BrowserStack and SauceLabs have kindly provided us with Open Source accounts capable of running 5 automated sessions in parallel (this is actually [a level of parallelism we're using](https://github.com/geb/geb/blob/master/module/geb-core/geb-core.gradle#L102) to keep our build quick). I assume that you are associated with LambdaTest, @ArpitLT, and that's something you'd be able to assist with. After we have an account we would switch [one of the browsers we're currently testing using BrowserStack](https://github.com/geb/geb/blob/master/module/geb-core/geb-core.gradle#L72) over to LambdaTest.
2. We'll need subsections in [the manual section about cloud browser testing](https://github.com/geb/geb/blob/master/doc/manual/src/docs/asciidoc/111-cloud-browsers.adoc) mentioning the plugin and cloud driver factory that you've added so that they are discoverable to users.

There might be some other minor points that will need addressing but I can do it on my own after the above two are resolved and after this PR get's merged.

Again, thanks for the impressive contribution, it's highly appreciated. Let's iron out the outstanding items and get this merged.

**Comment by ArpitLT** [comment]
Hi @erdi, 
Thanks for response.
1. **For LambdaTest Open Source Account** : Could you please sign up on our platform? [[Sign up here 👈](https://accounts.lambdatest.com/login)]  and let me know,I will enable 5 parallel automated session plan on your account in no time.
2. **For manual section about cloud browser testing** : I will commit changes till EOD and merge the PR.

**Comment by erdi** [comment]
Thanks @ArpitLT, my LambdaTest account name is marcin.erdmann.

**Comment by ArpitLT** [comment]
@erdi I have activated 5 parallel session named **Web+Mobile Browser Automation - 5 Parallel Tests** on your account. [Verify using Plan Page Link](https://accounts.lambdatest.com/billing/plans)
In case if doesn't show updated plan info, then please try to logout current session and login again.

I will update the PR in sometime about the documentation part and keep you posted, meanwhile you can start executing automation tests and view [Automation Dashboard](https://automation.lambdatest.com/) 

**Helpful Links** 

- [Desired Capabilities Generator](https://www.lambdatest.com/capabilities-generator/)
- [API Docs](https://www.lambdatest.com/support/docs/api-doc/)

**Comment by ArpitLT** [comment]
> 
> 
> Thanks @ArpitLT, my LambdaTest account name is `marcin.erdmann`.

Hey @erdi , I have pushed the modified cloud sample file with support for LambdaTest. To grant access for 5 parallel session for you, have started the process already.

**Comment by erdi** [comment]
Thanks again for the contribution, @ArpitLT. I have applied some minor changes and merged it.

**Comment by ArpitLT** [comment]
Thanks @erdi. I really appreciate your cooperation with my contribution to Geb community. Wishing a Happy New Year 2020.

**Pull request merged**
