### PR TITLE
Add month input module

### PR DESCRIPTION
**Pull request by mkutz**
See
https://www.w3.org/TR/2017/REC-html52-20171214/sec-forms.html#month-state-typemonth

Contributes to geb/issues#552

### CODE REVIEW

**Comment by mkutz** [comment]
Don't know, why this is not working. Will check on it tomorrow.

**Comment by erdi** [comment]
This looks good to be merged. Can you please resolve the conflict?

**Comment by mkutz** [comment]
Strange. It did work pre-merge, didn't it.

It seems we need to add another exception in [NonEmptyNavigator line 709](https://github.com/geb/geb/blob/master/module/geb-core/src/main/groovy/geb/navigator/NonEmptyNavigator.groovy#L709). Can you fix that @erdi? I cannot execute the test on my machine.

**Comment by erdi** [comment]
Cross browser tests do not run on PRs as it’s unlikely that PRs will
contain problems that manifest cross browser. Your PRs are exceptional with
regards to that. :)

Ok, I will fix it tomorrow for you.

**Comment by mkutz** [comment]
Thank you for fixing. I'm looking forward to 2.3.

Let me know if I can be of any help in the future.

**Comment by erdi** [comment]
You're welcome. I'm hoping to release as soon as everything scheduled for [2.3](https://github.com/geb/issues/milestone/29) is fixed, hopefully by the end of the year.

You can always help by providing ideas for new features, bug reports or PRs.

**Pull request merged**
