### PR TITLE
Add color input module

### PR DESCRIPTION
**Pull request by mkutz**
See geb/issues#549

### CODE REVIEW

**Comment by erdi** [comment]
Can you please rebase it onto latest master? This looks like it contains a lot of commits that are already in master...

**Comment by mkutz** [comment]
> Can you please rebase it onto latest master? This looks like it contains a lot of commits that are already in master...

I thought I did. Just realized it did not work as I intended. There should be only two commits.

**Comment by erdi** [comment]
I'm afraid it's still not right...

**Comment by erdi** [comment]
If that helps, you can always create a new branch based on master, cherry pick the required commits, delete the branch for this PR, rename your new branch to match the one for this PR and force push.

**Comment by mkutz** [comment]
Yeah, will do that. Closing this one.

**Pull request closed without merging**
