### PR TITLE
Patch for https://github.com/geb/issues/issues/477

### PR DESCRIPTION
**Pull request by mahileeb**
If select is set to null, deselect all if a multi select or throw an exception if not multiple

### CODE REVIEW

**Comment by antony** [comment]
Hi @mahileeb 

Unfortunately your commit fails CodeNarc validation - see the failed build link above for more details on this.

Also - and especially in the case of a testing framework, pull requests should include accompanying tests - ones which would fail prior to the code change, to both demonstrate the purpose of the fix, and to ensure that the fix actually works.

**Comment by mahileeb** [comment]
Sorry, fired this off quickly - will look at the failures and resubmit with a test

**Comment by mahileeb** [comment]
Hi @antony, I've fixed up code narc failures and added test cases for single and multi select cases

**Comment by erdi** [comment]
Thanks for the contribution, @mahileeb. FWIW I reworked it a bit: https://github.com/geb/geb/commit/72b1d3bc910c612a6611ae242cf98be20db8ceed.

**Comment by mahileeb** [comment]
Thanks @erdi!

**Pull request merged**
