### PR TITLE
Clearing inputs does not work on Chrome

### PR DESCRIPTION
**Pull request by mkutz**
Not to be merged, yet.

The test should fail on Chrome only.

### CODE REVIEW

**Comment by mkutz** [comment]
Seems like no tests have been executed on Sauce Labs 😕

**Comment by erdi** [comment]
Yeah, they are disabled on PRs because I'm worried that a rogue actor might steal credentials if the tests are executed. I will see how I can selectively enable them for certain PRs and let you know tomorrow.

**Comment by mkutz** [comment]
I see. I'm not 100% sure that the test will really fail. Couldn't try course I don't have any free time left on Sauce Labs. Several cues I followed suggested that auto-complete needs to be activated on the input's form, but there may be other factors I don't know about, yet.

I'd really love to have those tests running on Testcontainers (or something similar) instead of relying on an external service like Sauce Labs.

**Comment by erdi** [comment]
I had a look and it looks impossible to be able to pass credentials to certain forked PRs in CircleCI - it's either all of them or none. I think that for security reasons I should not be passing them to code I have no control over.

[It looks like the time has come to switch from using SauceLabs for running Chrome and FF tests on Linux and doing that in a docker container instead](https://github.com/geb/issues/issues/575). I did some thinking about it and It feels like it shouldn't be a hard thing to achieve using Testcontainers and will allow more advanced contributors like yourself to run at least some cross browser tests without the need for a paid SauceLabs account. It's something I'm intending to take a stab at over the upcoming weekend.

**Comment by mkutz** [comment]
Please let me know if I can be of any help. I'm currently maintaining several Geb + Testcontainers projects.

**Comment by erdi** [comment]
Thanks for the offer but I finally made some [significant progress on this](https://github.com/geb/geb/commit/ea724f210437cb8016892968c5fb7e7b1664c00f)  today and even got it [passing on CircleCI](https://circleci.com/gh/geb/geb/1571) after struggling for quite some time so it shouldn't be too long now. :)

**Comment by erdi** [comment]
[Success](https://github.com/geb/geb/commit/5225f50372885d7135b79ac56e4739f2c183c957)! If you rebase onto latest master you will be able to run `:module:geb-core:chromeLinuxTest` which will drive the browser in a docker container. I need to also change Firefox tests on Linux to run this way and change a couple of other places in the build where Chrome tests on Linux run at SauceLabs but this should be enough to get you going.

**Comment by mkutz** [comment]
That's great news! Looking forward to try it… hopefully tomorrow.

**Comment by mkutz** [comment]
I'm getting a `DriverCreationException`:
```
geb.module.PrefilledTextInputSpec > classMethod FAILED
    geb.driver.DriverCreationException: failed to create driver from callback 'GebConfig$_run_closure3@35a2c815'

        Caused by:
        org.testcontainers.containers.ContainerLaunchException: Container startup failed

            Caused by:
            org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception

                Caused by:
                org.testcontainers.containers.ContainerLaunchException: Could not create/start container

                    Caused by:
                    java.lang.reflect.UndeclaredThrowableException

                        Caused by:
                        java.lang.reflect.InvocationTargetException

                            Caused by:
                            com.github.dockerjava.api.exception.BadRequestException: {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"/opt/bin/entry_point.sh\\\": stat /opt/bin/entry_point.sh: no such file or directory\": unknown"}
```

**Comment by erdi** [comment]
It works on Mac locally and remotely on Linux on CircleCI so will be something specific to your env. Are you running it on the command line using Gradle? Does [this](https://github.com/docker/for-mac/issues/1396) help?

**Comment by mkutz** [comment]
I'm running `./gradlew clean :module:geb-core:chromeLinuxTest` from the command line on Ubuntu Linux 19.04. Will try again today.

**Pull request closed without merging**
