### PR TITLE
Let gebish.org/manual/ redirect to current manual

### PR DESCRIPTION
**Pull request by JacobAae**
A possible fix for https://github.com/geb/issues/issues/415
Instead of a 404, we could let it redirect to the current manual, which seems to be a fair default

### CODE REVIEW

**Comment by erdi** [comment]
Sorry, but I still believe that it should be a 404 and not a redirect. Apart from that, your solution does not solve the problem in full because http://www.gebish.org/foo/ also serves an unstyled page instead of a 404. 

We would need a generic solution for this and a test as well, please. :)

**Comment by JacobAae** [comment]
The trailing slashforward causes the static assets to be served from the wrong uri. This solution removes any trailing slashforward, and redirects to the page without it. This makes gebish.org/manual/ and other pages display the "Not Found" page. It does not actually serve a 404 status, but this is a general issue.

**Comment by JacobAae** [comment]
Added 404 status if Not Found page is the one displayed

**Comment by erdi** [comment]
Thanks yet again, @JacobAae!

**Pull request merged**
