### PR TITLE
Fix / improve reporting behaviour in conjunction with Spock's Retry annotation

### PR DESCRIPTION
**Pull request by thokari**
See https://github.com/geb/issues/issues/565

### CODE REVIEW

**Comment by erdi** [comment]
I haven't really looked into why yet but the tests you've added seem to be [failing on CI](https://circleci.com/gh/geb/geb/1409). I assume they passed for you locally when executed using `./gradlew check`?

**Comment by erdi** [comment]
Ignore me, this PR only contains a test that reproduces your problem. Reading your comment on geb/issues#565.

**Comment by thokari** [comment]
Well, the tests that I added passed at least, will see tomorrow what is the issue here...

**Comment by erdi** [comment]
Closing due to https://github.com/geb/issues/issues/565#issuecomment-483162205

**Pull request closed without merging**
