### PR TITLE
Change mailing list information in README.md.

### PR DESCRIPTION
**Pull request by PoohSunny**
mailing list information has been updated in [lists.html](https://github.com/geb/geb/blob/master/doc/site/src/ratpack/templates/includes/lists.html). But seems not to be updated in README.md.

### CODE REVIEW

**Comment by erdi** [comment]
Thanks for the contribution Yotaro. Well spotted.

This is not the only place where the address of the mailing list is incorrect. Would you also mind fixing it in the [manual](https://github.com/geb/geb/blob/master/doc/manual/src/chapters/140-project.md#support--development)?

Unfortunately we are in the process of migrating the Book of Geb from markdown to asciidoctor which means that it also need fixing [here](https://github.com/geb/geb/blob/master/doc/new-manual/src/docs/asciidoc/140-project.adoc#support--development).

It would be also helpful if you added yourself as a contributor [in the markdown version](https://github.com/geb/geb/blob/master/doc/manual/src/chapters/140-project.md#contributors) and [in the asciidoctor version](https://github.com/geb/geb/blob/master/doc/new-manual/src/docs/asciidoc/140-project.adoc#contributors). This way I could then pull it with one click of a button. :)

**Comment by PoohSunny** [comment]
I changed what you pointed out :) Please let me know if it needs some other changes.

**Comment by PoohSunny** [comment]
I don't understand why test fails. The test is passed when I run it in my local and It seems not to have relationship with my change... Can you please advise me how I can fix this...?

**Comment by erdi** [comment]
Don't worry about it, that test is flakey. It's not related to your change.

**Comment by PoohSunny** [comment]
@erdi Thank you :) I understand.

**Comment by erdi** [comment]
Thanks for the contribution!

**Pull request merged**
